def greeting(args):
    if args == "star":
                a=input("Enter your name: ")
                print(r"                    /\"")
                print(r"                   /  \"")
                print(r"                  /    \"")
                print(r"                 /      \"")
                print(r"                /        \"")
                print(r"               /          \"")
                print(r"______________/            \______________""")
                print(r"\                                        /""")
                print(f" \      {a}, wishing you happiness,     /""")
                print(r"  \            good health,            /""")
                print(r"   \and success in everything you do. /""")
                print(r"    \     May every day bring you    /""")
                print(r"     \    new reasons to smile      /""")
                print(r"      \    and feel grateful.      /""")
                print(r"       \                          /""")
                print(r"        \                        /""")
                print(r"        /                        \"""")
                print(r"       /                          \"""")
                print(r"      /                            \"""")
                print(r"     /                              \"""")
                print(r"    /               /\               \"""")
                print(r"   /               /  \               \"""")
                print(r"  /               /    \               \"""")
                print(r" /               /      \               \"""")
                print(r"/_______________/        \_______________\"""")
    
